# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Gaurav Chaudhari
title: Senior DevOps Engineer
email: gachaudhari02@gmail.com
phone: +91-7249313377 / +91-9960405722

# Social links
# twitter_username: facespics
github_username: gau02  
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __allspark
linkedin_username: gaurav-chaudhari-759568122
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_20200504_105859.jpg
about_content: | # this will include new lines to allow paragraphs
  I am very passionate about programming, operations skills and firm believer in continuous self improvement.   

  I am most skilled in: <mark>DevOps</mark> and <mark>Eating Burger</mark>


# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
