# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Gaurav Chaudhari
title: Senior DevOps Engineer
email: gachaudhari02@gmail.com
phone: +91-7249313377 / +91-9960405722

# Social links
# twitter_username: facespics
github_username: gau02  
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __allspark
linkedin_username: gaurav-chaudhari-759568122
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_20200504_105859.jpg
about_content: | # this will include new lines to allow paragraphs
  I am very passionate about programming, operations skills and firm believer in continuous self improvement.   

  I am skilled in: 
  
  Language and Technology - <mark>Core Java</mark> <mark>Linux</mark> <mark>R-Language</mark> <mark>Python</mark> <mark>Groovy</mark> <mark>YAML</mark> 
  
  Tools                   - <mark>Jenkins</mark> <mark>Ansible</mark> <mark>GitHub/Bitbucket</mark> <mark>Maven</mark> <mark>Gradle</mark> <mark>Nexus</mark> 
  <mark>Artifactory</mark> <mark>Docker(Basic)</mark> <mark>Kubernetes(Basic)</mark> 
  
  <mark>AWS(basic)</mark> <mark>Kafka</mark> <mark>Splunk</mark> <mark>GitHub Actions</mark>
# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Qualifications & Recognitions
more_content: | # this will include new lines to allow paragraphs
 **Bank Of America Global Recognition** : High Five Award, Bronze Award , Silver Award , Gold Award.
 
 **Intellect Design Arena Recognition** : Intellect Innovation Challenge Award for Data Science
# Footer
footer_show_references: true

# Build settings 
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
